a=str(input("enter the input:"))
print("the given has alphabets:",a.isalpha())
print("the given is alphanumeric:",a.isalnum())
print("the given is upper:",a.isupper())
print("the given is lower:",a.islower())
print("the given is digit:",a.isdigit())
print("the given is:",a.endswith("."))
#print(a.split(" "))
print(f"happy{a}")
#print("good".join(a))

b=a.split(" ")
print(b)
print(" ".join(b))
print(a[::-1])
print((a+" ")*2)
print(a.rstrip())
print(a.center(7))

